package com.maxsoft.stocktaker.dao;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteDatabase.CursorFactory;
import android.database.sqlite.SQLiteOpenHelper;
import android.util.Log;
import de.greenrobot.dao.AbstractDaoMaster;
import de.greenrobot.dao.identityscope.IdentityScopeType;

import com.maxsoft.stocktaker.dao.BrandDao;
import com.maxsoft.stocktaker.dao.UnitDao;
import com.maxsoft.stocktaker.dao.SizeDao;
import com.maxsoft.stocktaker.dao.CommodityCategoryDao;
import com.maxsoft.stocktaker.dao.SKUDao;
import com.maxsoft.stocktaker.dao.StocktakingRecordDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * Master of DAO (schema version 1): knows all DAOs.
*/
public class DaoMaster extends AbstractDaoMaster {
    public static final int SCHEMA_VERSION = 1;

    /** Creates underlying database table using DAOs. */
    public static void createAllTables(SQLiteDatabase db, boolean ifNotExists) {
        BrandDao.createTable(db, ifNotExists);
        UnitDao.createTable(db, ifNotExists);
        SizeDao.createTable(db, ifNotExists);
        CommodityCategoryDao.createTable(db, ifNotExists);
        SKUDao.createTable(db, ifNotExists);
        StocktakingRecordDao.createTable(db, ifNotExists);
    }
    
    /** Drops underlying database table using DAOs. */
    public static void dropAllTables(SQLiteDatabase db, boolean ifExists) {
        BrandDao.dropTable(db, ifExists);
        UnitDao.dropTable(db, ifExists);
        SizeDao.dropTable(db, ifExists);
        CommodityCategoryDao.dropTable(db, ifExists);
        SKUDao.dropTable(db, ifExists);
        StocktakingRecordDao.dropTable(db, ifExists);
    }
    
    public static abstract class OpenHelper extends SQLiteOpenHelper {

        public OpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory, SCHEMA_VERSION);
        }

        @Override
        public void onCreate(SQLiteDatabase db) {
            Log.i("greenDAO", "Creating tables for schema version " + SCHEMA_VERSION);
            createAllTables(db, false);
        }
    }
    
    /** WARNING: Drops all table on Upgrade! Use only during development. */
    public static class DevOpenHelper extends OpenHelper {
        public DevOpenHelper(Context context, String name, CursorFactory factory) {
            super(context, name, factory);
        }

        @Override
        public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {
            Log.i("greenDAO", "Upgrading schema from version " + oldVersion + " to " + newVersion + " by dropping all tables");
            dropAllTables(db, true);
            onCreate(db);
        }
    }

    public DaoMaster(SQLiteDatabase db) {
        super(db, SCHEMA_VERSION);
        registerDaoClass(BrandDao.class);
        registerDaoClass(UnitDao.class);
        registerDaoClass(SizeDao.class);
        registerDaoClass(CommodityCategoryDao.class);
        registerDaoClass(SKUDao.class);
        registerDaoClass(StocktakingRecordDao.class);
    }
    
    public DaoSession newSession() {
        return new DaoSession(db, IdentityScopeType.Session, daoConfigMap);
    }
    
    public DaoSession newSession(IdentityScopeType type) {
        return new DaoSession(db, type, daoConfigMap);
    }
    
}
